# Generated by Django 5.2 on 2025-04-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "buscode",
                    models.AutoField(
                        db_column="busCode", primary_key=True, serialize=False
                    ),
                ),
                ("buslicense", models.CharField(db_column="busLicense", max_length=20)),
                (
                    "bustype",
                    models.CharField(
                        blank=True, db_column="busType", max_length=25, null=True
                    ),
                ),
                (
                    "busstatus",
                    models.CharField(
                        blank=True, db_column="busStatus", max_length=2, null=True
                    ),
                ),
                (
                    "starttime",
                    models.DateTimeField(blank=True, db_column="startTime", null=True),
                ),
            ],
            options={
                "db_table": "bus",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "linecode",
                    models.AutoField(
                        db_column="lineCode", primary_key=True, serialize=False
                    ),
                ),
                (
                    "linename",
                    models.CharField(
                        blank=True, db_column="lineName", max_length=20, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "startlinetime",
                    models.DateTimeField(
                        blank=True, db_column="startLineTime", null=True
                    ),
                ),
                ("direction", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "line",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "permissioncode",
                    models.AutoField(
                        db_column="permissionCode", primary_key=True, serialize=False
                    ),
                ),
                (
                    "permissionname",
                    models.CharField(
                        blank=True, db_column="permissionName", max_length=50, null=True
                    ),
                ),
                (
                    "permissiondescribe",
                    models.CharField(
                        blank=True,
                        db_column="permissionDescribe",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "permission",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "rolecode",
                    models.AutoField(
                        db_column="roleCode", primary_key=True, serialize=False
                    ),
                ),
                (
                    "rolename",
                    models.CharField(
                        blank=True, db_column="roleName", max_length=50, null=True
                    ),
                ),
                (
                    "roledescribe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "role",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "stationcode",
                    models.AutoField(
                        db_column="stationCode", primary_key=True, serialize=False
                    ),
                ),
                (
                    "stationname",
                    models.CharField(
                        blank=True, db_column="stationName", max_length=50, null=True
                    ),
                ),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "station",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RolePermissionRef",
            fields=[
                (
                    "relationcode",
                    models.AutoField(
                        db_column="relationCode", primary_key=True, serialize=False
                    ),
                ),
                (
                    "permissioncode",
                    models.ForeignKey(
                        blank=True,
                        db_column="permissionCode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.permission",
                    ),
                ),
                (
                    "rolecode",
                    models.ForeignKey(
                        blank=True,
                        db_column="roleCode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permission_ref",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LineStationRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stationorder",
                    models.IntegerField(
                        blank=True, db_column="stationOrder", null=True
                    ),
                ),
                (
                    "linecode",
                    models.ForeignKey(
                        blank=True,
                        db_column="lineCode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.line",
                    ),
                ),
                (
                    "stationcode",
                    models.ForeignKey(
                        blank=True,
                        db_column="stationCode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.station",
                    ),
                ),
            ],
            options={
                "db_table": "line_station_ref",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sysuser",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                (
                    "loginname",
                    models.CharField(
                        blank=True, db_column="loginName", max_length=25, null=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "idcard",
                    models.CharField(
                        blank=True, db_column="idCard", max_length=25, null=True
                    ),
                ),
                (
                    "driving",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        db_column="role",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.role",
                    ),
                ),
            ],
            options={
                "db_table": "sysuser",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Scheduling",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tcnumber",
                    models.CharField(
                        blank=True, db_column="tcNumber", max_length=25, null=True
                    ),
                ),
                (
                    "tctime",
                    models.CharField(
                        blank=True, db_column="tcTime", max_length=20, null=True
                    ),
                ),
                (
                    "buslicense",
                    models.ForeignKey(
                        blank=True,
                        db_column="busLicense",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.bus",
                    ),
                ),
                (
                    "linecode",
                    models.ForeignKey(
                        blank=True,
                        db_column="lineCode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.line",
                    ),
                ),
                (
                    "endstation",
                    models.ForeignKey(
                        blank=True,
                        db_column="endStation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="endStation",
                        to="shuJuKu.station",
                    ),
                ),
                (
                    "startstation",
                    models.ForeignKey(
                        blank=True,
                        db_column="startStation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.station",
                    ),
                ),
                (
                    "usercode",
                    models.ForeignKey(
                        blank=True,
                        db_column="userCode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shuJuKu.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "scheduling",
                "managed": True,
            },
        ),
    ]
